/// Tongue-in-cheek closing lines shown at the bottom of every calculation.
///
/// The phrase is picked deterministically from the party id, so it stays the
/// same for a given calculation (no flicker on rebuild / reopen) while varying
/// between different calculations.
library;

const List<String> _uk = [
  'Закінчилось і слава Богу.',
  'Гроші скінчились, спогади залишились.',
  'Борги дружбу не псують. Нібито.',
  'Рахунок закрито. Майже.',
  'Хтось переплатив за цей цирк.',
  'Дякуємо за фінансові страждання.',
  'Бухгалтерія вижила.',
  'Наступного разу беремо багатших друзів.',
  'Спонсор вечора визначений.',
  'Все чесно. Напевно.',
  'Дружба пройшла фінансовий аудит.',
  'Комусь сьогодні буде соромно.',
  'Вечір закінчився, борги ні.',
  'Мінус гроші, плюс історія.',
  'Система знає, хто халявив.',
  'Справедливість відновлено.',
  'Майже без кровопролиття.',
  'Розрахунок завершено. Співчуваємо.',
  'Усі рівні. Особливо в боргах.',
  'Тепер офіційно можна розходитись.',
  'Гаманець плаче, але тихо.',
  'Це був дорогий спосіб провести час.',
  'Платіжки самі себе не закриють.',
  'Час платити за свої рішення.',
  'У когось сьогодні мінус на картці.',
  'Вечір був безцінний. Все інше має ціну.',
  'Банк уже насторожився.',
  'Наступного разу пікнік у дворі.',
  'Гроші знайдуть нового власника.',
  'Тепер зрозуміло, хто замовляв зайве.',
  'Слідство завершено.',
  'Всі підозрювані встановлені.',
  'Економічна катастрофа локалізована.',
  'Вклад кожного враховано. На жаль.',
  'Настав час великого переказу.',
  'Підраховано без хабарів.',
  'Дякуємо за участь у фінансовому експерименті.',
  'До нових необдуманих витрат.',
  'Тут може бути ваша реклама (дорого).',
  'Помилки молодості оплачуються зараз.',
  'Усі претензії приймаються після переказу.',
  'Халяву офіційно скасовано.',
  'Кожен отримав по заслугах. Майже.',
  'Суд визнав вас платоспроможним.',
  'Час відповідати за свої апетити.',
  'Дехто їв як король, тепер платить як підданий.',
  'Гроші не повернуть молодість, але повернуть борг.',
  'Безкоштовний сир знову подорожчав.',
  'Хто не платив — той тепер платить.',
  'Карма працює через банківські перекази.',
  'Спонсори заходу встановлені та допитані.',
  'Всі сміялися однаково, платять чомусь по-різному.',
  'Не всі фінансові рішення були хорошими.',
  'Настав момент фінансового каяття.',
];

const List<String> _en = [
  "It's over, thank God.",
  'The money is gone, the memories remain.',
  "Debts don't ruin friendships. Allegedly.",
  'Bill closed. Almost.',
  'Someone overpaid for this circus.',
  'Thanks for the financial suffering.',
  'Accounting survived.',
  'Next time we bring richer friends.',
  "Tonight's sponsor has been identified.",
  'All fair. Probably.',
  'Friendship passed a financial audit.',
  'Someone should be ashamed today.',
  "The night ended, the debts didn't.",
  'Minus money, plus a story.',
  'The system knows who freeloaded.',
  'Justice restored.',
  'Almost no bloodshed.',
  'Calculation complete. Our condolences.',
  "Everyone is equal. Especially in debt.",
  'You may now officially disperse.',
  'The wallet weeps, but quietly.',
  'That was an expensive way to spend time.',
  "The bills won't pay themselves.",
  'Time to pay for your decisions.',
  "Someone's card is in the red today.",
  'The night was priceless. Everything else has a price.',
  'The bank is already on alert.',
  'Next time, a picnic in the yard.',
  'The money will find a new owner.',
  "Now it's clear who over-ordered.",
  'Investigation closed.',
  'All suspects identified.',
  'Economic disaster contained.',
  "Everyone's contribution counted. Unfortunately.",
  'The time has come for the great transfer.',
  'Counted with no bribes.',
  'Thanks for taking part in the financial experiment.',
  "Here's to new reckless spending.",
  'Your ad could be here (expensive).',
  'The mistakes of youth are paid for now.',
  'All complaints accepted after the transfer.',
  'Freebies officially cancelled.',
  'Everyone got what they deserved. Almost.',
  'The court finds you solvent.',
  'Time to answer for your appetites.',
  'Some ate like a king, now pay like a subject.',
  "Money won't return your youth, but it will return the debt.",
  'Free cheese got pricier again.',
  "Whoever didn't pay now pays.",
  'Karma works through bank transfers.',
  "The event's sponsors identified and questioned.",
  'Everyone laughed equally, somehow they pay differently.',
  'Not all financial decisions were good.',
  'The moment of financial repentance has arrived.',
];

/// A stable closing line for [partyId] in the given [languageCode].
String quipForParty(String partyId, String languageCode) {
  final list = languageCode == 'uk' ? _uk : _en;
  if (list.isEmpty || partyId.isEmpty) return '';
  var hash = 0;
  for (final unit in partyId.codeUnits) {
    hash = (hash * 31 + unit) & 0x7fffffff;
  }
  return list[hash % list.length];
}
